# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171117_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemb',
            options={'permissions': (('view_itemb', 'View Item B'),)},
        ),
        migrations.AlterModelOptions(
            name='itemc',
            options={'permissions': (('view_itemc', 'View Item C'),)},
        ),
        migrations.AlterModelOptions(
            name='itemd',
            options={'permissions': (('view_itemd', 'View Item D'),)},
        ),
    ]
